### PR TITLE
Add Expense Date

### PR DESCRIPTION
**Pull request by ChristopherJohnston**
Add expense date field, defaulting to today's date. This is assignable in the expense form.
Group expenses list will sort by this date in descending order

This resolves issue #17

### CODE REVIEW

**Comment by ChristopherJohnston** [comment]
...sorry, in an attempt to continue working with this + PR #25 I have merged the commits in this PR. So if this is looked at after the categories one then all should be fine in terms of merging

**Comment by scastiel** [comment]
Hi @ChristopherJohnston, this is truly amazing, thanks for the contribution!

I’m very interested in storing/displaying an expense date, but I think categories require a bit more thinking… Do you think you could keep this PR only for the expense date? Hopefully this won’t be too much effort…

**Comment by ChristopherJohnston** [comment]
> Hi @ChristopherJohnston, this is truly amazing, thanks for the contribution!
> 
> I’m very interested in storing/displaying an expense date, but I think categories require a bit more thinking… Do you think you could keep this PR only for the expense date? Hopefully this won’t be too much effort…

sure - looks like all of this is behind your uneven split changes so I think it's easier that I close these PRs and start again - this one is a relatively simple change.

**Comment by ChristopherJohnston** [comment]
closing as superseded by #26

**Pull request closed without merging**
